server:
  port: 8080
spring:
  security:
    user:
      name: deep
      password: deepu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring-security-udemy
    username: root
    password: 456111197
    driver-class-name: com.mysql.cj.jdbc.Driver
